// src/constants.ts

export const PROJECT_TYPES: { [key: string]: string } = {
  mods: 'mod',
  resourcepacks: 'resourcepack',
  datapacks: 'datapack',
  shaders: 'shader',
  modpacks: 'modpack',
  plugins: 'plugin',
};

export const PROJECT_TYPE_LABELS: { [key: string]: string } = {
  mods: 'Mods',
  resourcepacks: 'Resource Packs',
  datapacks: 'Data Packs',
  shaders: 'Shaders',
  modpacks: 'Modpacks',
  plugins: 'Plugins',
};

export const PROJECT_TYPE_PATHS: { [key: string]: string } = {
  mods: 'mod',
  resourcepacks: 'resourcepack',
  datapacks: 'datapack',
  shaders: 'shader',
  modpacks: 'modpack',
  plugins: 'plugin',
};

export const LATEST_PATCHES: { [key: string]: number } = {
  '1.21': 10, '1.20': 6, '1.19': 4, '1.18': 2, '1.17': 1, 
  '1.16': 5, '1.15': 2, '1.14': 4, '1.12': 2, '1.8': 9, '1.7': 10, 
  '1.6': 4, '1.5': 2, '1.4': 7, '1.3': 2, '1.2': 5, '1.1': 0, '1.0': 0
};

export const BANNED_KEYWORDS = ['lgbtq', 'pride', 'lgbtq+', 'lgbt+', 'LGBT+', 'p/ride', 'gay', 'furry', 'trans'];

export const BANNED_IMAGE_URLS = [
    'https://cdn.modrinth.com/data/AANobbMI/images/af966be7e960742619014059147cad1cdc4e2f2d.png',
    'https://cdn.modrinth.com/data/qANg5Jrr/40269a95e1e4237e9204e0f8b2172cbf4658c9c1_96.webp',
    'https://cdn.modrinth.com/data/74aTv108/images/071b0da4b0956d18fe61c0d1c37f3a92dc3a3f0a.webp',
    'https://cdn.modrinth.com/data/cached_images/071b0da4b0956d18fe61c0d1c37f3a92dc3a3f0a.webp',
    'https://cdn.modrinth.com/data/cached_images/e63175a54ed1c0484e07f9e71bd426244220b51b.png'
];

export const BANNED_EXACT_SLUGS: string[] = [
    'pride!',
    'p-ride',
    'joy',
    "lgbt-slime",
    "lgbtnt",
    "lgbtq+-flags",
    "lgbtq+happy-ghast",
    "pridepack",
    "pridegui",
    "pridegui-legacy",
    "pridebones",
    "pridegui-legacy-light",
    "pridegui-light",
    "prideful",
    "pridepack-legacy",
    "lgbeet",
    "os-pride-bookshelves",
    "gaytopia-server-pack",
    "lesbian-gui-texture-pack+",
    "os-lgbtq+-pride-cats",
    "pride-cb",
    "pride-title",
    "pridemclogo",
    "pride-harnesses",
    "pride-ghast",
    "pridestone-pride",
    "pridesniffer",
    "pridestone-transgender",
    "pridestone-gay",
    "pridestone-bisexual",
    "pridestone-lesbian",
    "pridestone-nonbinary",
    "pridestone-aroace",
    "pridestone-pansexual",
    "pridestone-genderfluid",
    "pridestone-asexual",
    "pridestone-aromantic",
    "pridestone-agender",
    "pridestone-intersex",
    "pridestone-genderqueer",
    "pridestone-demisexual",
    "vivillon-pride-patterns",
    "undopia-pride-bees",
    "undopia-pride-logo",
    "poetic-pride",
    "minimalist-pride-trans",
    "tooltip_transgender+5clr-frame-altbg",
    "rts-pride-bees",
    "minimalist-pride-rainbow",
    "tooltip_lesbian+7clr-full",
    "tooltip_transgender+5clr-full",
    "rainbow-pride-logo",
    "minimalist-pride-nonbinary",
    "tooltip_bisexual+3clr-full",
    "tooltip_pansexual+3clr-full",
    "tooltip_transgender+5clr-frame",
    "tooltip_genderfluid+5clr-full",
    "tooltip_transgender+3clr-full",
    "tooltip_bisexual+3clr-frame-altbg",
    "tooltip_genderfluid+5clr-frame-altbg",
    "tooltip_lesbian+7clr-frame-altbg",
    "tooltip_agender+7clr-frame-altbg",
    "tooltip_asexual+4clr-full",
    "tooltip_lesbian+5clr-full",
    "tooltip_transgender+3clr-frame-altbg",
    "tooltip_pansexual+3clr-frame",
    "tooltip_bigender+7clr-frame-altbg",
    "tooltip_genderqueer+3clr-frame",
    "tooltip_bisexual+3clr-frame",
    "tooltip_lesbian+5clr-frame",
    "tooltip_polysexual+3clr-full",
    "tooltip_transgender+3clr-frame",
    "tooltip_intersex+split-mono-bg-frame",
    "tooltip_agender+7clr-full",
    "tooltip_intersex+mono-frame",
    "tooltip_polyamory+5clr-frame",
    "tooltip_polyamory+5clr-full",
    "tooltip_bigender+7clr-frame",
    "tooltip_genderfluid+5clr-frame",
    "tooltip_genderqueer+3clr-frame-altbg",
    "tooltip_intersex+mono-frame-altbg",
    "tooltip_lesbian+7clr-frame",
    "tooltip_pansexual+3clr-frame-altbg",
    "tooltip_polyamory+5clr-frame-altbg",
    "tooltip_polysexual+3clr-frame",
    "tooltip_polysexual+3clr-frame-altbg",
    "tooltip_genderqueer+3clr-full",
    "tooltip_bigender+7clr-full",
    "tooltip_miaspec+5clr-full",
    "tooltip_lesbian+5clr-frame-altbg",
    "tooltip_fiaspec+5clr-frame",
    "tooltip_aromantic+5clr-full",
    "tooltip_miaspec+5clr-frame-altbg",
    "tooltip_asexual+4clr-frame",
    "tooltip_fiaspec+5clr-full",
    "tooltip_aromantic+5clr-frame-altbg",
    "tooltip_agender+7clr-frame",
    "tooltip_transgender+5clr-full-turned",
    "tooltip_fiaspec+5clr-frame-altbg",
    "tooltip_miaspec+5clr-frame",
    "tooltip_bisexual+3clr-full-turned",
    "tooltip_aromantic+5clr-frame",
    "tooltip_asexual+4clr-frame-altbg",
    "tooltip_lesbian+5clr-frame-altbg-turned",
    "tooltip_lesbian+7clr-full-turned",
    "tooltip_lesbian+7clr-frame-altbg-turned",
    "tooltip_lesbian+7clr-frame-turned",
    "tooltip_agender+7clr-frame-turned",
    "tooltip_transgender+5clr-frame-turned",
    "tooltip_pansexual+3clr-frame-altbg-turned",
    "tooltip_transgender+3clr-frame-turned",
    "tooltip_bisexual+3clr-frame-turned",
    "tooltip_lesbian+5clr-full-turned",
    "tooltip_aromantic+5clr-frame-altbg-turned",
    "tooltip_bisexual+3clr-frame-altbg-turned",
    "tooltip_pansexual+3clr-full-turned",
    "tooltip_genderfluid+5clr-frame-turned",
    "tooltip_bigender+7clr-frame-turned",
    "tooltip_genderqueer+3clr-full-turned",
    "tooltip_aromantic+5clr-frame-turned",
    "tooltip_transgender+3clr-full-turned",
    "tooltip_transgender+5clr-frame-altbg-turned",
    "tooltip_transgender+3clr-frame-altbg-turned",
    "tooltip_polysexual+3clr-frame-altbg-turned",
    "tooltip_bigender+7clr-full-turned",
    "tooltip_polyamory+5clr-frame-altbg-turned",
    "tooltip_miaspec+5clr-frame-altbg-turned",
    "tooltip_asexual+4clr-frame-turned",
    "tooltip_genderqueer+3clr-frame-altbg-turned",
    "tooltip_polysexual+3clr-frame-turned",
    "tooltip_pansexual+3clr-frame-turned",
    "tooltip_miaspec+5clr-frame-turned",
    "tooltip_agender+7clr-frame-altbg-turned",
    "tooltip_polysexual+3clr-full-turned",
    "tooltip_asexual+4clr-full-turned",
    "tooltip_lesbian+5clr-frame-turned",
    "tooltip_polyamory+5clr-frame-turned",
    "tooltip_asexual+4clr-frame-altbg-turned",
    "tooltip_miaspec+5clr-full-turned",
    "tooltip_fiaspec+5clr-frame-turned",
    "tooltip_bigender+7clr-frame-altbg-turned",
    "tooltip_genderfluid+5clr-full-turned",
    "tooltip_genderfluid+5clr-frame-altbg-turned",
    "tooltip_polyamory+5clr-full-turned",
    "tooltip_aromantic+5clr-full-turned",
    "tooltip_fiaspec+5clr-frame-altbg-turned",
    "tooltip_genderqueer+3clr-frame-turned",
    "tooltip_agender+7clr-full-turned",
    "tooltip_fiaspec+5clr-full-turned",
    "cpft",
    "ashen-bumblezone-pride-bees",
    "trans-jian",
    "lesbian-xiphos",
    "blades-of-pride-03-nonbinary-hand-and-a-half",
    "tooltip_gay-mlm+7clr-full",
    "tooltip_gay-mlm+7clr-frame",
    "tooltip_aroace+5clr-frame-altbg",
    "tooltip_aroace+5clr-full",
    "tooltip_aromantic-spectrum+5clr-frame-altbg-turned",
    "tooltip_aromantic-spectrum+5clr-frame",
    "tooltip_asexual-spectrum+4clr-frame-altbg",
    "tooltip_gay-mlm+5clr-frame",
    "tooltip_gay-mlm+7clr-frame-altbg",
    "tooltip_gay-mlm+5clr-frame-altbg",
    "tooltip_gay-mlm+5clr-full",
    "tooltip_aroace+5clr-frame",
    "tooltip_aromantic-spectrum+5clr-frame-altbg",
    "tooltip_asexual-spectrum+4clr-frame",
    "tooltip_asexual-spectrum+4clr-full",
    "tooltip_aromantic-spectrum+5clr-full",
    "tooltip_gay-mlm+7clr-frame-turned",
    "tooltip_gay-mlm+5clr-full-turned",
    "tooltip_gay-mlm+5clr-frame-turned",
    "tooltip_aromantic-spectrum+5clr-full-turned",
    "tooltip_aroace+5clr-full-turned",
    "tooltip_gay-mlm+7clr-frame-altbg-turned",
    "tooltip_gay-mlm+5clr-frame-altbg-turned",
    "tooltip_gay-mlm+7clr-full-turned",
    "tooltip_aroace+5clr-frame-turned",
    "tooltip_asexual-spectrum+4clr-frame-altbg-turned",
    "tooltip_asexual-spectrum+4clr-frame-turned",
    "tooltip_aroace+5clr-frame-altbg-turned",
    "tooltip_aromantic-spectrum+5clr-frame-turned",
    "tooltip_asexual-spectrum+4clr-full-turned",
    "intersex-glow-berries",
    "rainbow-shields",
    "asexual_hearts",
    "trans-hotbar-and-xp-bar",
    "bi-hotbar-and-xp-bar",
    "mlm-hotbar-and-xp-bar",
    "ace-hotbar-and-xp-bar",
    "tooltip_rainbow+7clr-full",
    "tooltip_rainbow+7clr-frame",
    "tooltip_rainbow+7clr-frame-turned",
    "tooltip_rainbow+7clr-full-turned",
    "winters-banner-tweaks",
    "lesbian-pride-logo",
    "gay-pack",
    "gay-flowering-hotbar",
    "gay-logo",
    "gay-plaza-resource-pack",
    "begaydocrime",
    "lesbian-xp-bar",
    "lesbian-hearts"
];

export const BANNED_SLUG_KEYWORDS: string[] = [
    'pride', 'lgbt', 'lgbtq', 'gay', 'furry',
];
